name: AdventOfCodeBadges
on:
  push:
    paths:
      - adventofcode/
    branch: main
  workflow_dispatch: # allow to manually start the workflow

# push:                                          # (disabled) run on push, be carefull with this setting
# as the workflow should only be triggered at a rate lower than
# 4 times a hour to keep traffic on aoc site low
jobs:
  # equivalent to batch changes. stop prior workflows if still running to run the latest only
  cancel-runs:
    name: CancelAnyCurrentRunning
    runs-on: ubuntu-latest
    if: github.repository == 'sheldonhull/algorithmswithgo.com' # Prevent forks from running this to be nice
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # workflow: .adventofcode.yml # only applies to scheduled and gives a warning anyway
  update:
    name: UpdateAdventBadges
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # clones your repo
      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: ${{ secrets.AOC_USERID }} # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }} # secret containing session code, see setup on how to obtain
      - uses: stefanzweifel/git-auto-commit-action@v4 # Step that pushes these local changes back to your github repo
        with:
          commit_message: "chore(docs): 💾 update adventofcode badges"
          file_pattern: README.md
